### ISSUE TITLE
How we can use @setDataFrame

### ISSUE THREAD

**Issue by phuochau** [ossrs/srs-librtmp#10]
Many thanks for cool library. I'm using it to create node C++ addon and it's working very well.

Now I have a problem, I try to publish flv file to rtmp server (nginx-rtmp). Our abstract flow is in below:

```javascript
while(!eof) {
 1. read tag headers by srs_flv_read_tag_header
 2. read tag data by srs_flv_read_tag_data
 3. send tag via srs_rtmp_write_packet (return 0, sent successfully)
}
```
But seem nginx-rtmp does not understand `onMetadata`. I have tried OBS to publish same flv file to nginx-rtmp and I see in the log, it receive `@setDataFrame`

So do we need encode our data to AMF0 before sending (I have tried and same result)? Or how can send `@setDataFrame`. Thanks so much!

**Comment by phuochau** [comment]
@winlinvip do you have any ideas?

**Comment by winlinvip** [comment]
Please use `srs_amf0_*` to parse the FLV `onMetadata` to `@setDataFrame`(an amf0 object).
