### ISSUE TITLE
URL中的参数问题

### ISSUE THREAD

**Issue by Keyon11** [ossrs/srs-librtmp#11]
SRS中srs_generate_normal_tc_url定义如下：
string srs_generate_normal_tc_url(string ip, string vhost, string app, int port, string param)
srs-librtmp中定义：
string srs_generate_normal_tc_url(string ip, string vhost, string app, int port)
对比两者发现，srs-librtmp中的URL不支持带参数的。目前需要使用srs-librtmp的srs_rtmp_bandwidth_check做带宽测试，由于SRS需要key参数，而srs-librtmp由于上述函数限制没有提供key参数。请问如何解决？

**Comment by jamken** [comment]
我这边也碰到相同的问题，服务器我们是采用srs，其中需要在url中传递参数用在认证权限。客户端我们采用srs-librtmp，发现按照常规的调用流程下，srs-librtmp会将url中...后的参数过滤掉，tcurl中只是将非参数部分传递给服务器。

参考代码，应该是srs-librtmp拼接tcUrl时的一个bug， srs的拼接函数与srs-librtmp不一样。请作者留意一下这个问题，不能自相矛盾吧

**Comment by winlinvip** [comment]
Fixed.
