### ISSUE TITLE
vs2010 project的使用问题

### ISSUE THREAD

**Issue by Victoryczz** [ossrs/srs-librtmp#12]
你好，我在将srs-librtmp下载到本地，使用vs2010打开工程，debug模式编译，平台是win32：
 
![image](https://user-images.githubusercontent.com/22150464/29485119-14a0c040-84ff-11e7-9d2c-f81435d3ad72.png)

结果会报以下错误，请问这是什么原因？
![image](https://user-images.githubusercontent.com/22150464/29485122-19f8f8d2-84ff-11e7-9e7b-126ca49c30d6.png)

**Comment by winlinvip** [comment]
Dup to #25
