### ISSUE TITLE
setsockopt问题

### ISSUE THREAD

**Issue by david-fan** [ossrs/srs-librtmp#13]
hi,
Error	23	error C2664: 'int setsockopt(SOCKET,int,int,const char *,int)' : cannot convert argument 4 from 'timeval *' to 'const char *'	c:\users\david\downloads\srs-librtmp-srs2.0\src\srs\srs_librtmp.cpp	35523
这个要怎么解决？

**Comment by winlinvip** [comment]
Fixed.
