### ISSUE TITLE
vhost 解析有bug

### ISSUE THREAD

**Issue by arsee11** [ossrs/srs-librtmp#22]
vhost=www.abc.com&autkey=afkdajdk， vhost 会被解析成www.abc.com&autkey 。其中"&"字符不能识别成分隔符, 在 srs_vhost_resolve 函数中。

**Comment by winlinvip** [comment]
Fixed in https://github.com/ossrs/srs/commit/c5f31570cd2954ca20eea547cd52a7eb18987c48
