### ISSUE TITLE
library not working anymore

### ISSUE THREAD

**Issue by Skroopa** [ossrs/srs-librtmp#24]
After downloading last version of srs-librtmp library can't connect to any rtmp:// (ERROR_SOCKET_CONNECT on srs_rtmp_connect_server).

**Comment by superxrb** [comment]
我也遇到了同样的问题。

**Comment by chuanjiong** [comment]
@Skroopa @superxrb 

marked ipv6 is ok for me.

int srs_hijack_io_create_socket(srs_hijack_io_t ctx, srs_rtmp_t owner)
{
    SrsBlockSyncSocket* skt = (SrsBlockSyncSocket*)ctx;

    //skt->family = AF_INET6;
    //skt->fd = ::socket(skt->family, SOCK_STREAM, 0);   // Try IPv6 first.
    //if (!SOCKET_VALID(skt->fd)) {
        skt->family = AF_INET;
        skt->fd = ::socket(skt->family, SOCK_STREAM, 0);   // Try IPv4 instead, if IPv6 fails.
    //}
    if (!SOCKET_VALID(skt->fd)) {
        return ERROR_SOCKET_CREATE;
    }

**Comment by winlinvip** [comment]
SRS3还不稳定，我暂时将master切回了SRS2.
