### ISSUE TITLE
Compiling on Visual Studio 2019

### ISSUE THREAD

**Issue by ghost** [ossrs/srs-librtmp#25]
Hi,

I'm trying to compile srs-librtmp on visual studio 2019 in windows 10. The project loads and is upgraded to the latest toolset and I then compile and get these errors.

![image](https://user-images.githubusercontent.com/264872/70375519-89bb5b00-18f6-11ea-9680-ac912ac46522.png)

For this line
![image](https://user-images.githubusercontent.com/264872/70375522-93dd5980-18f6-11ea-8fce-32d9db076345.png)

In "srs_librtmp.cpp".

Many thanks for the help.

**Comment by winlinvip** [comment]
The original commit:

1. Support build srs-librtmp by VS2015. 2.0.267, https://github.com/ossrs/srs/commit/316628632bcbc088a852fe8a094d8f12acd98bcc and https://github.com/ossrs/srs/commit/c6732d0fbbeb144220304c7c12dfda1d88df7456 and https://github.com/ossrs/srs/commit/08bbbc5414fd0b34214f59275178556726b8694d and https://github.com/ossrs/srs/commit/01a4503ceba411ceca8ae68eb5b25081840c0884
1. Support VS2015, https://github.com/ossrs/srs-librtmp/commit/9eab92c7060b187143c051ae4b6080db2815371c

**Comment by ghost** [comment]
Thanks for that I can now confirm it compiles for me. I'm finding when I do a release compile it gives the error of.
![image](https://user-images.githubusercontent.com/264872/71364893-5c78d900-2595-11ea-9603-173e78cec025.png)
