### ISSUE TITLE
下面sps,pps 致　srs-librtmp　挂掉 

### ISSUE THREAD

**Issue by jhkwei** [ossrs/srs-librtmp#4]
00 00 00 01 67 64 00 2a ad 84 01 0c 20 08 61 00 43 08 02 18 40 10 c2 00 84 2b 50 3c 01 13 f2 a0 
00 00 00 01 68 ee 3c b0 00 00 00 01 06 e5 01 e9 80 00 00 00 01 65 b8 00 00 0c 9d 70 67 d6 81 af

**Comment by winlinvip** [comment]
我看看啥原因。

**Comment by winlinvip** [comment]
这个pps数据实际上包含了三个数据：

```
00 00 00 01 68 ee 3c b0  // PPS
00 00 00 01 06 e5 01 e9 80 // SEI
00 00 00 01 65 b8 00 00 0c 9d 70 67 d6 81 af // IDR
```

**Comment by winlinvip** [comment]
除了有用的帧，都丢了就行了。

**Comment by winlinvip** [comment]
https://github.com/ossrs/srs-librtmp/commit/03efcc5654c4f20d5a0b940402c21431d0b6cb6a
不忽略aud，ios可能有用。据悟空和豹哥说
