### ISSUE TITLE
srs-librtmp 没有提供释放rtmp packet data的接口

### ISSUE THREAD

**Issue by jhkwei** [ossrs/srs-librtmp#7]
我是用 C 语言去调用 srs-librtmp 的
1） 调用 srs_rtmp_read_packet(rtmp, &type, &timestamp, &data, &size)  拉流时，data 没有相应的释放接口，在 c++ 时有 delete 
2）同时多个拉流时，外部 epoll 之类没有得到相对应的socket 的句柄的接口，如果有这样的接口， 是不是要另外提供，play, play2 请求接口， 以及与之对应的srs_rtmp_read_packet 接口。

**Comment by winlinvip** [comment]
这个倒是个问题，没有提供释放char* data的函数。

**Comment by winlinvip** [comment]
对于第二个问题，如果需要使用非同步的socket，那可以用srs_hijack_io_xxx，实现这些API后，在include srs_librtmp.hpp之前定义宏`SRS_HIJACK_IO`，就可以用你自己的socket了。

```
srs_hijack_io_create_socket(srs_hijack_io_t ctx, srs_rtmp_t owner)
```
这个API可以用来绑定这个io和rtmp的关系。

**Comment by winlinvip** [comment]
释放data的接口：`srs_rtmp_free_packet`
